### ISSUE TITLE
Longitudinal data?

### ISSUE THREAD

**Issue by zcc33** [jsilve24/stray#29]
Hi, I apologize in advance if this is not the right place to ask this. I was wondering if you had considered how best to handle data, in the context of your model, which is longitudinal. For example, in certain microbiome datasets there are multiple measurements coming from the same organism, and this may change the structure of the covariance prior. I enjoyed reading your paper and thanks for any thoughts you may have!

**Comment by jsilve24** [comment]
This is the right place. It just may take me a bit of time to reply. My apologies in advance. 

Justin

**Comment by jsilve24** [comment]
Yes I have thought a lot about it :)

From your comment it sounds like you may have not just one set of repeat measurements but perhaps a longitudinal study with multiple organisms being sampled repeatedly. There are many ways to handle this. In our paper we discuss two examples, non-linear Gaussian Process based marginally LTP models or DLM based marginally LTP models. We are still working on the DLM implemenation in stray but the non-linear GP implementation is set up. There is even a vignette on using the GPs (called *basset* because its a lazy learner) https://jsilve24.github.io/stray/articles/non-linear-models.html. Notably the vignette just deals with modeling a single time-series not time-series from multiple individuals, but its really going to be quite similar likely (see next comment). Finally note that its pretty simple to just use *pibble* but set  a bunch of random effects terms and a corresponding Gamma matrix that has some non-zero co-variance between samples from the same individual/organism (up to you how that covariance is structured (e.g., you could have an AR covariance structure where samples more closely related in time have higher covariance etc...). Similarly gamma could also have structure that specified non-zero covariance for different organisms (perhaps your studying monkeys that live in families etc...).  

# Modeling multiple time-series with basset
Just like how you can set up some correlation structure between samples using *pibble* you can specify a kernel function that gives the structure you want to the covariance. For example, you could have an RBF kernel specifying covariance between time-points within an organisms and a second kernel specifying the covariance between samples from different organisms. 


Does this help? Happy to answer further questions.
